services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPOONACULAR_API_KEY: ${SPOONACULAR_API_KEY:-}
    volumes:
      - .:/var/www/html
